{% set version = "1.78.0" %}

package:
  name: grpc-bazel-rules
  version: {{ version }}

source:
  - url: https://github.com/grpc/grpc/archive/v{{ version }}.tar.gz
    sha256: e2ace790a5f2d0f83259d1390a816a33b013ea34df2e86084d927e58daa4c5d9
    patches:
      - 0001-Adjust-to-support-xla-specific-features.patch

build:
  number: 0
  noarch: generic
  skip: True  # [not linux64]

requirements:
  run_constrained:
    - libgrpc {{ version }}.*

test:
  commands:
    - test -f ${PREFIX}/share/bazel/grpc/bazel/python_rules.bzl  # [unix]

about:
  home: https://grpc.io
  dev_url: https://github.com/grpc/grpc
  doc_url: https://grpc.io/docs
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Bazel rules for gRPC
  description: Bazel rules for gRPC

extra:
  recipe-maintainers:
    - conda-forge/grpc-cpp
