context:
  version: "1.70.1"

package:
  name: grpc-bazel-rules
  version: ${{ version }}

source:
  url: https://github.com/grpc/grpc/archive/v${{ version }}.tar.gz
  sha256: c4e85806a3a23fd2a78a9f8505771ff60b2beef38305167d50f5e8151728e426

build:
  number: 0
  noarch: generic

requirements:
  run_constraints:
    - libgrpc ${{ version }}.*

tests:
  - package_contents:
      files:
        - share/bazel/grpc/bazel/python_rules.bzl

about:
  homepage: https://grpc.io/
  repository: https://github.com/grpc/grpc
  license: Apache-2.0
  license_file: LICENSE
  summary: Bazel rules for grpc

extra:
  recipe-maintainers:
    - conda-forge/grpc-cpp
